### ISSUE TITLE
multicast-receiver crashes with ERR_PROTO

### ISSUE THREAD

**Issue by engr-mubashir** [bbc/nghq#7]
The behaviour of multicast-receiver is unstable i.e. it receives a file/folder and keeps waiting for any new packet (which is okay as per flow). But if I send again a file/folder it throws ‘ERR_PROTO’ and ‘nghq_session_recv()’ fails with code -1. I did enable the debug for both NGHQ and NGTCP2 during setup but somehow NGTCP2 library does not debug anything. See attached logs

[multicast-sender_log.txt](https://github.com/bbc/nghq/files/3477323/multicast-sender_log.txt)
[multicast-receiver-error_log.txt](https://github.com/bbc/nghq/files/3477325/multicast-receiver-error_log.txt)

PS: Oracle VirtualBox VM (Ubuntu v18.04.2 LTS ) with libev v4.25

**Comment by samhurst** [comment]
It looks like you might be simply re-running the sender application without restarting the receiver. This means that the sender will be re-using previously closed streams, which the receiver correctly flags as an error. The receiver is only intended to receive data from a single server, but there's currently no way for it to know that the server has finished and gone away. In our I-D, this is signalled using a "Connection: Close" HTTP header on the final resource that is being sent, but I don't think the examples currently support this.

**Comment by engr-mubashir** [comment]
Thanks for the explanation and you have rightly guessed, how I was using the sender and the receiver applications. Surely, this is not a bug but can be a future extension so closing it.
